#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
        /*)   app_path=$link ;;
        *)    app_path=$APP_HOME$link ;;
    esac
done
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

if ! command -v uname > /dev/null 2>&1
then die "ERROR: UNAME not found"
fi

case $( uname ) in
    Linux* | Darwin* | CYGWIN* | MINGW* | MSYS*)
        have_cygwin=false
        case $( uname ) in
            CYGWIN* | MINGW* | MSYS*)
                have_cygwin=true
        esac
    ;;
    *)
        die "Unsupported OS: $( uname )"
esac

if ! command -v java > /dev/null 2>&1
then die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

JAVACMD=java

# Increase the maximum file descriptors if we can.
if ! "$have_cygwin" && ! grep -q "${MAX_FD}" /proc/sys/fs/file-max 2>/dev/null
then
    MAX_FD_LIMIT=$( ulimit -H -n ) ||
        warn "Could not query maximum file descriptor limit"
    case $MAX_FD_LIMIT in
        '' | soft) :;;
        *)
            ulimit -n "$MAX_FD_LIMIT" ||
                warn "Could not set maximum file descriptors to $MAX_FD_LIMIT"
    esac
fi

# Collect all arguments for the java command;
GRADLE_OPTS=${GRADLE_OPTS:-""}
DEFAULT_JVM_OPTS=${DEFAULT_JVM_OPTS:-""}

set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "$@"
